### ISSUE TITLE
Parsing of Thread No.304583189 failed. Thread will be skipped. (+119 other errors)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2685]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.14.11.0 userscript
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
URL: https://boards.4channel.org/vg/

TypeError: Cannot read property 'no' of undefined
at Object.buildThreads (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=4chan%2520X.user.js&id=08528a8c-f0a5-4bbb-ab25-17a578fec437:12056:108)
    at Object.buildCatalogPart (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=4chan%2520X.user.js&id=08528a8c-f0a5-4bbb-ab25-17a578fec437:12367:23)
    at Function.fn (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=4chan%2520X.user.js&id=08528a8c-f0a5-4bbb-ab25-17a578fec437:12352:23)
    at MessagePort.execTask (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=4chan%2520X.user.js&id=08528a8c-f0a5-4bbb-ab25-17a578fec437:5191:19)

**Comment by ccd0** [comment]
same issue: #2686 #2687 #2688 #2689 #2690 #2691 #2692 #2693 #2694 #2695 #2696 #2698 #2699 #2700 #2701 #2702 #2703 #2704 #2705 #2706 #2707 #2708 #2709 #2710

**Comment by ccd0** [comment]
Should be fixed as of 1.14.20.1.

**Comment by ccd0** [comment]
#2711 #2712 #2713 #2714

**Comment by ccd0** [comment]
#2715 #2716 #2717 #2718

**Comment by bakugo** [comment]
The index still fails to load if the sort order is set to "Last reply"

**Comment by ccd0** [comment]
Thanks, fixed.

**Comment by ccd0** [comment]
#2729 #2730 #2731 #2732 #2733 #2734 #2735 #2736 #2737 #2738 #2739 #2740 #2741

**Comment by ccd0** [comment]
#2719 #2720 #2721 #2722 #2723 #2724 #2725 #2726 #2727 #2728

**Comment by ccd0** [comment]
#2742 #2743 #2744 #2746 #2747 #2748 #2749 #2750 #2751 #2752 #2753 #2754 #2755

**Comment by ccd0** [comment]
#2757 #2758 #2759 #2760 #2761 #2762 #2763 #2764 #2766 #2767 #2768 #2769 #2770 #2771 #2772 #2773 #2774 #2776
