### ISSUE TITLE
11.33.7 : Expand images results in two images being expanded

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#938]
I have the native extension disabled, but for some reason, when i click on an image to expand it, it expands two images, one which is thumbnail sized and one which is the full image size. Any idea what's going on?

Using grease monkey 3.8 on pale moon 26.2.1. if it helps.

Edit : Oddly enough, disabling 4chan x's image expansions in the settings fixes it, but i can still expand images...

Also i have relative timestamps turned off but they still display for me...and worse, the tooltip wont go away...

I installed the beta version of 4chan X and removed it, but i think its interfering with the stable version of 4chan x in some way.

Even with the 4chanx plugin uninstalled, i can still click on settings which activates a buggy looking settings menu at the bottom of the page, although it is non-functional (you cannot save settings or anything). about:addons just says that i have no user scripts, yet there is clearly some left over user script there...

**Comment by ccd0** [comment]
This sounds consistent with the native extension with cookies / local storage disabled. Are you blocking inline scripts? 4chan X needs one or the other to disable the inline extension. Also, make sure you have "Disable Native Extension" checked in 4chan X and not just in the native extension's settings, which won't save if local storage isn't available.

**Comment by Question2** [comment]
I do have cookies from 4chan blocked, but im not sure what you mean by "local storage".

Just to be safe i removed the umatrix addon to make sure it wasnt blocking anything. Theres no changes. 4chanX's settings (it says 4chanX at the top of the settings page) say that relative timestamps and image expansion are off, yet i still get the relative timestamps and image expansions. Its also set to disable native extension.

**Comment by Question2** [comment]
I tried re-enabling cookies and now most of the features are working, except for the "open new threads in new tab" one. I have it enabled, but everytime i make a new thread, it doesn't open it in a new tab.

**Comment by ccd0** [comment]
Local storage and cookies are disabled by the same setting in Firefox / Pale Moon. 4chan X should work with cookies disabled. With cookies disabled, what do you get if you paste
`document.documentElement.classList.contains('js-enabled')`
and
`Config.disableAll`
in the Javascript console?

As for "open new threads in new tab", what you want is the "Open Post in New Tab" setting under "Quick Reply".

**Comment by Question2** [comment]
Wheres the java script console?

I do have that option checked under quick reply settings, but its not working even with cookies turned on...

**Comment by ccd0** [comment]
> Wheres the java script console?

Press F12 and select "Console".

**Comment by Question2** [comment]
For document.documentElement.classList.contains('js-enabled')

I get "True"

And for Config.disableAll

I get false.

im seeing a ton of errors though, like

[05:13:28.579] Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. @ https://s.4cdn.org/css/photon.653.css:1
[05:13:28.580] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://s.4cdn.org/css/photon.653.css:1
[05:13:28.585] Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. @ https://s.4cdn.org/css/futabanew.653.css:1
[05:13:28.585] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://s.4cdn.org/css/futabanew.653.css:1
[05:13:28.641] Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. @ https://s.4cdn.org/css/tomorrow.653.css:1
[05:13:28.642] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://s.4cdn.org/css/tomorrow.653.css:1
[05:13:28.647] Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. @ https://s.4cdn.org/css/yotsubanew.653.css:1
[05:13:28.648] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://s.4cdn.org/css/yotsubanew.653.css:1
[05:13:28.653] Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. @ https://s.4cdn.org/css/burichannew.653.css:1
[05:13:28.654] Expected media feature name but found '-webkit-min-device-pixel-ratio'. @ https://s.4cdn.org/css/burichannew.653.css:1

**Comment by i-cant-git** [comment]
Disable console output for CSS, those are unrelated.

**Comment by ccd0** [comment]
I suspect the native extension not being disabled is due to a race condition. I'll see what I can do about it.

Regarding the new tab thing, can you check if any errors appear when it happens, either in the Javascript console (Control+Shift+K) or browser console (Control+Shift+j)? And can you post your exported settings?

**Comment by ccd0** [comment]
On the new tab issue, you may want to try temporarily disabling any other extensions you have to see if one of them is causing it. I can easily see this being caused by a misconfigured ad blocker or script blocker.

**Comment by ccd0** [comment]
Can you check whether it works without cookies in the beta version?

**Comment by Question2** [comment]
I just tried the current beta version and it still goes haywire without cookies. Without cookies, expanding images results in double images just like before.

Console shows no errors with CSS unchecked.

**Comment by ccd0** [comment]
What do you get if you type `Config` in the console?
Does this happen on a fresh profile?

**Comment by Question2** [comment]
Where am i supposed to type it in the console? The filter output part? Because that just gives me no results...

Yes, it happens on a fresh profile. As long as i have cookies blocked, i get double image expansion.

**Comment by ccd0** [comment]
Press F12, select "Console", and type it in the little line at the bottom.
Actually, make it
`JSON.stringify(Config)`

**Comment by Question2** [comment]
[16:45:07.424] JSON.stringify(Config)

Thats the output, nothing else.

**Comment by ccd0** [comment]
Is this with a fresh profile?
What do you get from `2+2`?

**Comment by Question2** [comment]
That should be with a fresh profile, as i disabled the stable version of 4chanx and installed the beta version of 4chanx.

--
[16:53:56.790] 2+2
[16:53:56.796] 4

**Comment by ccd0** [comment]
> That should be with a fresh profile, as i disabled the stable version of 4chanx and installed the beta version of 4chanx.

Not what I mean.

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Question2** [comment]
Okay heres with a fresh profile :

**Comment by ccd0** [comment]
Can you try installing 
https://a.pomf.cat/pgqwyb.user.js
and then seeing what it prints in the console? Turn off "Net", "CSS", "JS", and "Security", so only "Logging" messages are showing.

**Comment by Question2** [comment]
? It doesnt print anything, that page just askes me to install 4chanx beta 1.12.01. 

This page right? https://a.pomf.cat/pgqwyb.user.js

**Comment by ccd0** [comment]
When you load 4chan.

**Comment by Question2** [comment]
Alright, so basically you want me to install 1.12.01 then try loading 4chan to see what the console prints? I just tried loading /a/ and the console prints nothing in the logging section.

**Comment by ccd0** [comment]
Yes, that's it.
Can you try the same thing with this one?
https://a.pomf.cat/rgzrdi.user.js

**Comment by Question2** [comment]
Ok, it just printed this 

[17:53:55.660] "Conf['Disable Native Extension'] = " true
[17:53:55.660] "$.hasStorage = " true

**Comment by ccd0** [comment]
This is with cookies disabled, right?
How precisely are you disabling cookies?
What do you get when you type `localStorage.getItem('x')` in the console?

**Comment by Question2** [comment]
Yes, that is with cookies disabled. I just right clicked -> view page info -> permissions and disabled cookies from there.

I get this

--
[17:59:10.015] localStorage.getItem('x')
[17:59:10.017] [Exception... "The operation is insecure."  code: "18" nsresult: "0x80530012 (SecurityError)"  location: "debugger eval code Line: 1"]

**Comment by ccd0** [comment]
Okay, I can reproduce your problem now. I had been testing with cookies globally disabled. Working on a fix.

**Comment by Question2** [comment]
Cool, thanks!

**Comment by ccd0** [comment]
The fix should be in the newest beta version (v1.12.0.2). Does it work on your end?

**Comment by Question2** [comment]
Yep, the double image expansion seems to be fixed now, thanks.

**Comment by ccd0** [comment]
Do the other issues happen in a fresh profile, or is there some setting you have to set to make them happen?

**Comment by Question2** [comment]
Hmm, i just checked and the post dates seem to be working fine now, the tooltip popup is no longer permanent.

"Create new thread in a new tab" was apparently working...but for some reason, pale moon was shoving all the newly created tabs to the very end of the tab bar, so I didnt notice them at all. This didnt used to happen, not sure what changed. Im not sure if thats fixed now...i will have to get back to you on that.

**Comment by Question2** [comment]
Okay just tested it again. For some reason, as long as i have "create new thread in new tab" checked, the new tab gets created but only at the end of the tab bar.

So if i have 500 tabs only, the new tab gets created as tab 501, instead of the tab right next to the one i'm viewing.

If i right click a click and select to open in new tab, it will properly create the new tab next to the one i'm viewing, but 4chan x will not do that for some reason.

**Comment by ccd0** [comment]
4chan X uses `GM_openInTab`. If that's putting the tab in the wrong place, it needs to be fixed in the port of Greasemonkey you're using:
https://github.com/janekptacijarabaci/greasemonkey/releases/latest

Alternatively you could check if Greasemonkey 1.15 works better.

**Comment by Question2** [comment]
I tried installing greasemonkey 1.15.1-signed on firefox, and that doesnt appear to work with the latest stable version of 4chanX. 4chanX dissapeared entirely, and trying to re-install it doesnt give me the install popup with grease monkey.

I read a post where you said that the problem is with pale moon, but greasemonkey 3.8 on firefox also has the problem where the tabs open in the wrong place.

**Comment by ccd0** [comment]
> I tried installing greasemonkey 1.15.1-signed on firefox
It won't work on current Firefox, but it will work on Pale Moon. Although I tested it just now, and it doesn't seem to solve the tabs problem.

> greasemonkey 3.8 on firefox also has the problem where the tabs open in the wrong place
I'm not seeing it.

**Comment by Question2** [comment]
Not sure what to say then, any way to test it to see whats causing it?

**Comment by ccd0** [comment]
I'm seeing the tabs problem in Pale Moon but not in Firefox. Might be a long shot, but maybe if you can figure out why you're seeing it in Firefox, you can fix it in Pale Moon. Do you see it in Firefox on a fresh profile?

**Comment by ccd0** [comment]
I made a separate issue for the new tabs thing at #980.

**Comment by ccd0** [comment]
@Question2
You should be able to make the new tabs open where you want by opening your Pale Moon settings, selecting `Tabs`, and checking `Insert related tabs next to the current tab`.
